### ISSUE TITLE
This is so cool

### ISSUE THREAD

**Issue by CompuIves** [Noviny/react-codesandboxer#6]
Thank you so much for building this! Is there anything else you need from the API, and would it make sense to link this in the CodeSandbox repo/docs as well?

Again, thank you for building this!

**Comment by Noviny** [comment]
Hi!

If you wanted to link this in the repo/docs, I would be absolutely thrilled! I was actually looking to reach out to you about this in the next couple of days, once I shipped the next update. Would love to chat about the niche this is fulfilling, and how the API could support it more.

my current biggest desires from the api are:
- resolving cors problems so I can use fetch to submit data to the json endpoint and get the url back as an optional redirect, as chrome is blocking the form submission as a popup atm.
- possibly being able to pass the type of sandbox to override auto-detection if I want.

And once again, thanks so much for making CodeSandbox. It's been making our lives a lot easier, and it's a truly great resource to have access to.

**Comment by Noviny** [comment]
Additional thing, I want to make sure the way this is implemented is healthy for codesandbox, so if you have ideas or suggestions for how I should change it, I'd be happy to make sure it works for you.

**Comment by CompuIves** [comment]
Ah that completely makes sense, I agree with both your requests. I'll make sure to implement them tomorrow!

One thing I would really love to see is something like an `Embed` component, a React component that takes arguments and just renders an iframe with the embed. I'm not sure how feasible this is with the current API, but I'd love to help make it happen 😄.

I'm also working on a library for CodeSandbox that opens up the bundler for many other use cases. Would be cool if we could talk about that too 😄. Are you on Discord? Maybe we can talk about some ideas there, our Discord is here: https://discord.gg/KE3TbEZ.

Again, thank you so much for this library, it will make it so much easier for others to create sandboxes on the fly.

**Comment by Noviny** [comment]
Closing as codesandboxer is now in the codesandbox documentation. 🎉
